---
framework: jest
preRun:
  command:
    - npm i
    - npm run react
postMerge: 
  pattern:
    - "test/**/*.{js|jsx}"
preMerge:
  pattern:
    - "test/**/*.{js|jsx}"
postRun:
  command:
    - node --version
version: 1.0



