---
framework: jest
preRun:
  command:
    - npm i
    - npm run react
postMerge: 
  pattern:
    - "test/**/*.js"
preMerge:
  pattern:
    - "test/**/*.js"
postRun:
  command:
    - node --version
version: 1.0
