---
framework: jest
preRun:
  command:
    - npm i
postMerge: 
  pattern:
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/linear-test.js"
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
postRun:
  command:
    - node --version
version: 1.0

